version: '3.8'

services:
  backend:
    build: ./backend
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
    command: python run.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5002
    depends_on:
      - backend

networks:
  default:
    driver: bridge 